#!/usr/bin/env bash
#
# cronvr
# A shell script to record and manage IP camera
# 
# Heavily inspired by u/oddworld19 from r/homelab

set -e

PRGNAM="cronvr"
VERSION="0.5"
CWD="$(pwd)"
STARTTIME=$(/bin/date +"%Y%m%d")"-"$(/bin/date +"%H").$(/bin/date +"%M").$(/bin/date +"%S")
TODAY=$(/bin/date +"%A")
CONFIG=("/etc/$PRGNAM" "/usr/local/etc/$PRGNAM" "$HOME/.config/$PRGNAM" "$HOME/.$PRGNAM" "$CWD/$PRGNAM.conf")
CONFOVERRIDE=0

# Default vars, can be overridden in conf
archive="5"    # number of days to retain
length="900"   # number of seconds for each recording

## Sourced in Configuration ##
basedir=""
rtsp_path=""
cam_user=""
cam_pass=""
protocol=""
declare -A camera

usage () {
    printf "%s [Version: %s]\n" "$PRGNAM" "$VERSION"
    printf "A shell script to record and manage IP cameras.\n\n"
    printf "Usage: %s (--config /path/to/config) record|cleanup\n" "$PRGNAM"
    printf "Declare the config file with %s --config /path/to/conf\n" "$PRGNAM"
    printf "Otherwise, looks for config file in the following locations:\n"
    printf "\n"
    for conf in "${CONFIG[@]}"; do
        printf "    %s\n" "$conf"
    done
    printf "\n"
}

get_config () {
    if [ "$CONFOVERRIDE" -ne 0 ]; then
        return 0
    fi

    #loop thru config array
    for conf in "${CONFIG[@]}"; do
        if [ -r "$conf" ]; then
            CONFIG="$conf"
            return 0
        fi
    done

    # Check if variables are set
    for vars in "$basedir" "$rtsp_path" "$cam_user" "$cam_pass"; do
        if [ -z "$vars" ]; then
            printf "ERROR: Cannot find config file or variables unset.\n"
            return 1
        fi
    done
}

source_config () {
    get_config || exit 1
    source "$CONFIG"
}

record () {
    source_config
    # Dependency check
    if ! test -x /usr/bin/ffmpeg; then
      printf "ERROR: /usr/bin/ffmpeg not found\n" >&2
      exit 1
    fi

    for cam_name in "${!camera[@]}"; do
        printf "[%s %s] Starting record of %s at %s...\n" "$PRGNAM" "$VERSION" "$cam_name" "${camera[$cam_name]}" >&2
        mkdir -p "$basedir/$cam_name/$TODAY" || exit 1
        ( /usr/bin/ffmpeg -rtsp_transport $protocol -i "rtsp://$cam_user:$cam_pass@${camera[$cam_name]}:$port/$rtsp_path" -vcodec copy -acodec copy -t "$length" $basedir/$cam_name/$TODAY/$STARTTIME.mkv ) >/dev/null 2>&1 &
    done
}

cleanup () {
    source_config
    # Remove files older than $archive days, default 5
    find "$basedir" -type f -mtime "$archive" -exec rm {} \;
}

main () {
    if [ "$#" -eq 0 ]; then
        usage
        exit 1
    fi

    while [ "$#" -gt 0 ]; do
        case "$1" in
            --config|-c|-f)
                CONFOVERRIDE=1
                CONFIG="$2"
                shift 2 ;;

            record)
                record
                shift 1 ;;

            cleanup)
                cleanup
                shift 1 ;;

            *)
                usage
                exit 1 ;;
        esac
    done
}

main "$@"
